# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityB', models.IntegerField()),
                ('customernameB', models.CharField(max_length=200)),
                ('customerAddressB', models.TextField()),
                ('payAmtB', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('totalprizeB', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mobileB', models.IntegerField(blank=True, null=True)),
                ('isFullPayB', models.BooleanField(default=False)),
                ('timestampB', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameP', models.CharField(max_length=200)),
                ('categoryP', models.CharField(max_length=200)),
                ('priceP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestampP', models.DateTimeField(auto_now_add=True)),
                ('imageP', models.FileField(upload_to='media/image/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='productB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist'),
        ),
    ]
