# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobileB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
