# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=200)),
                ('custlast', models.CharField(max_length=200)),
                ('custemail', models.CharField(max_length=255, unique=True)),
                ('custmobile', models.CharField(max_length=15, unique=True)),
                ('custpassword', models.CharField(max_length=200, unique=True)),
                ('custtimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
