# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_followproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followproperty',
            name='propertyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.mainproperty'),
        ),
    ]
